<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<meta http-equiv="Content-type" content="text/html;charset=UTF-8" />
<title><?=$this->getTitle()?></title>
<link rel="stylesheet" type="text/css" media="screen" href="/css/global.css" />

<?=$this->headStyle()?>

</head>
<body>
<?=$this->partial('header.phtml')?>
<?=$this->getContent(); ?>
<?=$this->partial('footer.phtml')?>

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>

<?=$this->headScript()?>

</body>
</html>